export const ADD_LETTER_TO_TILE = "ADD_LETTER_TO_TILE"
export const FETCH_ALLOWED_GUESSES = "FETCH_ALLOWED_GUESSES"
export const ADD_ALLOWED_GUESSES = "ADD_ALLOWED_GUESSES"
export const LOADING_ALLOWED_GUESSES = "LOADING_ALLOWED_GUESSES"

export const FETCH_WORD_TO_GUESS = "FETCH_WORD_TO_GUESS"
export const ADD_WORD_TO_GUESS = "ADD_WORD_TO_GUESS"
export const LOADING_WORD_TO_GUESS = "LOADING_WORD_TO_GUESS"